i = 0;
sprites[i++] = spr_card_back;
sprites[i++] = spr_card_1;
sprites[i++] = spr_card_2;
sprites[i++] = spr_card_3;
sprites[i++] = spr_card_4;
sprites[i++] = spr_card_5;
sprites[i++] = spr_card_6;
sprites[i++] = spr_card_7;
sprites[i++] = spr_card_8;
sprites[i++] = spr_card_9;
return;